apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-monorepo
resources:
  - ../../base
  - docker-pull-secret.yaml
images:
  - name: ghcr.io/gpt-next/monorepo/test
    newTag: 5cbed4440e66df11b48c64bb6a5e9a1ca6ea75b2
  - name: ghcr.io/gpt-next/monorepo/test2
    newTag: a5bc15068991b2e14f0e537d12bbe208ee2221a1
