apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-monorepo
resources:
- ../../base
- docker-pull-secret.yaml
images:
- name: ghcr.io/gpt-next/monorepo/test
  newTag: aaad514a7b7fa32c6b19257e675fc5979ce96410
- name: ghcr.io/gpt-next/monorepo/test2
  newTag: aaad514a7b7fa32c6b19257e675fc5979ce96410
