apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-monorepo
resources:
- ../../base
- docker-pull-secret.yaml
images:
- name: test
  newName: ghcr.io/gpt-next/monorepo/test
  newTag: latest
- name: test2
  newName: ghcr.io/gpt-next/monorepo/test2
  newTag: latest
- name: ghcr.io/gpt-next/monorepo/test
  newTag: 98f752189f3202d70204cab04e0928815eb83b86
- name: ghcr.io/gpt-next/monorepo/test2
  newTag: 98f752189f3202d70204cab04e0928815eb83b86
