apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-monorepo
resources:
- ../../base
- docker-pull-secret.yaml
images:
- name: ghcr.io/gpt-next/monorepo/test
  newTag: eeca96063627d0b719c76394e5d29a3aa646907e
- name: ghcr.io/gpt-next/monorepo/test2
  newTag: eeca96063627d0b719c76394e5d29a3aa646907e
