apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-monorepo
resources:
- ../../base
- docker-pull-secret.yaml
images:
- name: ghcr.io/gpt-next/monorepo/test
  newTag: v1.0.2-rc1
- name: ghcr.io/gpt-next/monorepo/test2
  newTag: v1.0.1
