apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  labels:
    app.kubernetes.io/name: test-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: test-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-service
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - name: test
          image: ghcr.io/gpt-next/monorepo/test
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
